### ISSUE TITLE
Compiling fails on 5.1.15; do_gettimeofday was removed

### ISSUE THREAD

**Issue by gw2princeps** [JohnMH/chipone_ts#1]
Hi there, 
Found my old cw1515 and after fighting for several ours with the touchscreen I came across this cool repository. 
Trying to compile this with make does not work; it is complaining about  

do_gettimeofday(&data->last_irq_event);
line 94 in chipone_main.c 

A quick websearch told me, that this method was removed in 5.0. Since I'm not very proficient in C I cant fix this myself. Would be amazing if you (or somebody with more knowledge) could take a look at this issue. 

Thanks a lot for all your work into this project :)

**Comment by JohnMH** [comment]
Unfortunately, as the README states:

> I do not have the CW1515 I was using to test this, so I can't really do much in the way of further work on this driver.

**Comment by gw2princeps** [comment]
Thats not my point. This entire thing does not compile any longer, because 

1. do_gettimeofday was deprecated a long time ago and finally removed.
2. Some asm library broke. 

Asides from that, I was able to fix these issues and make the driver compile again. It kinda works, still figuring out how to fix some of the issues. 
Will PR when the time is right.

**Comment by JohnMH** [comment]
My point being that I am not actively maintaining this. I have no way to test this code, even if I can get it to compile against a modern kernel.

On July 5, 2019 3:36:53 PM UTC, "Alex D." <notifications@github.com> wrote:
>Thats not my point. This entire thing does not compile any longer,
>because 
>
>1. do_gettimeofday was deprecated a long time ago and finally removed.
>2. Some asm library broke. 
>
>Asides from that, I was able to fix these issues and make the driver
>compile again. It kinda works, still figuring out how to fix some of
>the issues. 
>Will PR when the time is right.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/JohnMH/chipone_ts/issues/1#issuecomment-508796936

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cnZary** [comment]
try https://github.com/JohnMH/chipone_ts/pull/2 
`make hi10`
Working on Ubuntu 18.04, But there are some bugs

**Comment by JohnMH** [comment]
On Thursday, August 22, 2019 9:24:40 AM MST Zary wrote:
> try https://github.com/JohnMH/chipone_ts/pull/2
> make hi10
> Working on Ubuntu 18.04, But there are some bugs

"Ubuntu 18.04" isn't really all that useful. What kernel version, and vanilla 
kernel or Ubuntu kernel?

-- 
John M. Harris, Jr. <johnmh@splentity.com>
Splentity
https://splentity.com/

**Comment by JohnMH** [comment]
Fixed by @cnZary over a year ago, now merged.

Still not tested, but it does compile for me on Fedora.
